### ISSUE TITLE
Find all @Help annotations in classpath

### ISSUE THREAD

**Issue by FRosner** [FRosner/repl-helper#8]
### Problem

In order to fix https://github.com/FRosner/spawncamping-dds/issues/280, we might need to scan the current classpath for `@Help` annotations.
### Solution

There should be another constructor to helper, which does not take a single class but scans the current classpath.
### References
- http://software.clapper.org/classutil/#source_code_repository
- http://stackoverflow.com/questions/520328/can-you-find-all-classes-in-a-package-using-reflection and http://bill.burkecentral.com/2008/01/14/scanning-java-annotations-at-runtime/ => https://github.com/ronmamo/reflections

**Comment by FRosner** [comment]
```
org.reflections.ReflectionsException: Can't resolve member named mockedMethodWithHelp for class de.frosner.dds.core.DDSTest$MockedServer
	at org.reflections.util.Utils.getMemberFromDescriptor(Utils.java:94)
	at org.reflections.util.Utils.getMethodsFromDescriptors(Utils.java:101)
	at org.reflections.Reflections.getMethodsAnnotatedWith(Reflections.java:443)
	at de.frosner.replhelper.Helper.<init>(Helper.scala:29)
	at de.frosner.replhelper.Helper$.apply(Helper.scala:129)
	at de.frosner.dds.core.DDS$.<init>(DDS.scala:38)
	at de.frosner.dds.core.DDS$.<clinit>(DDS.scala)
```

**Comment by FRosner** [comment]
I will include a package filter option to see if this helps in terms of speed for https://github.com/FRosner/spawncamping-dds/issues/280

**Comment by FRosner** [comment]
Or we can include a classpath filter that somehow ignores the jars from spark and only takes extra ones... Dunno if we can distinguish this somehow.
